#!/bin/bash

echo "================================"
echo " Choose Menu
echo "================================"
echo "1. Add user"
echo "2. list user"
echo "3. Who login"
echo "4. Settings"
echo "5. Detail server"
echo "6. Check port open"
echo "7. Monitoring bandwith"
echo "8. Uninstall"
echo "0. Quit"
