#!/bin/bash

echo "Service OpenSSH		:"
echo "Service Dropbear		:"
echo "Service OpenVPN		:"
echo "Service Websocket		:"
echo "Service Squid		:"
echo "Service OHP		:"
echo "Service Shocks		:"
echo "Service SlowDNS-Server	:"
echo "Service SlowDNS-Client	:"
echo "Service UDPcustom		:"
echo "Service Nginx		:"
echo "Service SSLH		:"
echo "Service BadVPN/UDPGW	:"
echo "Service Xray_Vmess_TLS	:"
echo "Service Xray_Vmess_NonTLS	:"
echo "Service Xray_Vmess_gRPC	:"
echo "Service Xray_Vless_TLS	:"
echo "Service Xray_Vless_NonTLS	:"
echo "Service Xray_Vless_gRPC	:"
echo "Service Trojan_gRPC	:"
echo "Service Trojan_WS		:"
echo "Service Shadowsocka_WS	:"
echo "Service Shadowsocks_gRPC	:"
